# Plantilla de configuración para MongoDB
# Copiar este archivo como 'secrets.toml' y completar con tus credenciales

# MongoDB Atlas
mongo_uri = "mongodb+srv://username:password@cluster.mongodb.net/"
db_name = "ksb_presupuesto"

# MongoDB Local (alternativa)
# mongo_uri = "mongodb://localhost:27017/"
# db_name = "ksb_presupuesto"